### ISSUE TITLE
Use DB23 PCB connector from the A520

### ISSUE THREAD

**Issue by chris-jh** [EmberHeavyIndustries/AMI-RGB2VGAULTIMATE#1]
Hi

Wondering if you can do a modified version to instead use the PCB DB23 connector from all the unused A520 Modulators.

I would modify myself, but you have not included the KiCad or Eagle project files. ( i am unsure which one you have done this in )

Unless you don't mind me at some point recreating it fully in KiCad and publish on github.

i see on PCBWay you have license has Share A Like, so would leave your credit on there and link back to the original GitHub.

**Comment by EmberHeavyIndustries** [comment]
No issues at all to me if you want to recreate it on KiCad as per the SHare A Like licensing terms, it released it that way with that exact purpose in mind !
If you want original project files, I can attach here the EasyEDA json (I made it in EasyEDA for quickness, not yet had time to port it to KiCad mylself).

[RGB2VGA_V3.1.zip](https://github.com/EmberHeavyIndustries/AMI-RGB2VGAULTIMATE/files/14374421/RGB2VGA_V3.1.zip)
